name: 'Issues to Json'
description: 'Generate JSON from GitHub issues'
author: 'xaoxuu'

inputs:
  github_token:
    description: 'GitHub token'
    required: false
    default: 'xxx'

runs:
  using: 'node20'
  main: 'dist/index.js'